"""link para imagens nas noticias

Revision ID: 141f38963be4
Revises: ca481abf2017
Create Date: 2025-11-17 23:02:31.881866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141f38963be4'
down_revision = 'ca481abf2017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
