"""empty message

Revision ID: 277a84cc2ffe
Revises: 141f38963be4
Create Date: 2025-11-18 01:26:20.245476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277a84cc2ffe'
down_revision = '141f38963be4'
branch_labels = None
depends_on = None


def upgrade():
    # Make the migration idempotent: check existing columns before altering.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = [c['name'] for c in inspector.get_columns('news')]

    # Perform add/drop only if necessary
    with op.batch_alter_table('news', schema=None) as batch_op:
        if 'image' not in existing_cols:
            batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        if 'image_path' in existing_cols:
            batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
