"""delete on cascade noitifications.news_id

Revision ID: a6a9170c9a87
Revises: 5855c033b93f
Create Date: 2025-11-17 16:17:46.248506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a9170c9a87'
down_revision = '5855c033b93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_news_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_news_id_fkey'), 'news', ['news_id'], ['id'])

    # ### end Alembic commands ###
