"""delete on cascade dleeting news

Revision ID: ca481abf2017
Revises: a6a9170c9a87
Create Date: 2025-11-17 16:20:54.834149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca481abf2017'
down_revision = 'a6a9170c9a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_notifications_notification_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_notifications_notification_id_fkey'), 'notifications', ['notification_id'], ['id'])

    # ### end Alembic commands ###
